name: tests-windows
on:
  workflow_call:
    inputs:
      version:
        type: string
        default: ""
      run_id:
        type: string
        default: ""
      archs:
        type: string
        default: '["wow64", "win64"]'
      event:
        type: string
        default: "push"

jobs:
  tests:
    runs-on: ubuntu-latest

    container:
      image: rbernon/winetest-windows:stable
      options: --user root --device=/dev/kvm --device=/dev/net/tun --cap-add NET_ADMIN -p 8006:8006

    strategy:
      matrix:
        arch: ${{ fromJson(inputs.archs) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache/restore@v4
        with:
          path: /storage
          key:
            storage-${{ github.run_id }}
          restore-keys: |
            storage

      - name: Download
        if: ${{ matrix.arch != 'win64' }}
        uses: actions/download-artifact@v4
        with:
          name: build-linux-win32
          github-token: ${{ github.token }}
          repository: rbernon/winetest
          run-id: ${{ inputs.run_id }}

      - name: Download
        if: ${{ matrix.arch == 'win64' }}
        uses: actions/download-artifact@v4
        with:
          name: build-linux-win64
          github-token: ${{ github.token }}
          repository: rbernon/winetest
          run-id: ${{ inputs.run_id }}

      - name: Execute
        timeout-minutes: 90
        run: |
          $PWD/test-windows ${{ inputs.version }} ${{ matrix.arch }} ${{ inputs.event }}

      - name: Upload
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-${{ inputs.version }}-${{ matrix.arch }}.report
          path: /data/winetest.report

  clean:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup
        uses: rbernon/workflow-cleanup@main
        with:
          workflow: all
